apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: notifier-daemonset
  namespace: pod-lifecycle-notifier
  labels:
    app: notifier-daemonset
spec:
  selector:
    matchLabels:
      app: notifier-daemonset
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: notifier-daemonset
    spec:
      volumes:
        - name: shared-volume
          emptyDir: { }
      initContainers:
        - name: init-container
          image: dwdraju/alpine-curl-jq:latest
          command:
            - "/bin/sh"
            - "-c"
            - "export SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount && export TOKEN=$(cat ${SERVICEACCOUNT}/token) && export CACERT=${SERVICEACCOUNT}/ca.crt && curl --cacert ${CACERT} --header \"Authorization: Bearer ${TOKEN}\" -X GET https://kubernetes.default.svc/version | jq .gitVersion -r > /mnt/init-container/kubeapi-version"
          volumeMounts:
            - name: shared-volume
              mountPath: "/mnt/init-container"
      containers:
        - name: notifier
          image: robachmann/pod-lifecycle-notifier:1.2.0
          resources:
            requests:
              cpu: 5m
              memory: 128Mi
            limits:
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: notifier-config
            - secretRef:
                name: notifier-secret
          env:
            - name: KUBERNETES_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_NODE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: KUBERNETES_POD_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
          volumeMounts:
            - name: shared-volume
              mountPath: "/mnt/init-container"
