apiVersion: v1
kind: Secret
metadata:
  name: notifier-secret
  namespace: pod-lifecycle-notifier
type: Opaque
stringData:
  CALLBACK_MS_TEAMS_URI: ""
  CALLBACK_TELEGRAM_BOT_TOKEN: ""
  CALLBACK_TELEGRAM_CHAT_ID: ""
